Update test_script

diff --git a/testing/test_script b/testing/test_script
--- a/testing/test_script
+++ b/testing/test_script
@@ -14,7 +14,7 @@
 
 # because we're using pipe to tee and output to a file, it's
 # useful to make sure the pipe doesn't hide the error 
-set -e
+# set -e
 set -o pipefail
 
 error=0
@@ -76,10 +76,22 @@ LOGFILE=${datestamp}/testing.log
           OUTPUT=${datestamp}/${i}_$datestamp.out
           if [ $NCORE -gt 1 ]; then
           	mpirun -n $NCORE $1 < ./test_cases/$i > $OUTPUT
+            if ["$?" -ne "0"]; then
+              kill $PID_HANG
+              exit 1
+            fi
           else
           	$1 < ./test_cases/$i > $OUTPUT
+            if ["$?" -ne "0"]; then
+              kill $PID_HANG
+              exit 1
+            fi
           fi
           python testing.py $OUTPUT $i | tee -a $LOGFILE
+          if ["$?" -ne "0"]; then
+              kill $PID_HANG
+              exit 1
+          fi
       done
       echo Tests completed in $SECONDS seconds on $(date) | tee -a $LOGFILE
       echo ----------------------------------------------------------------------\n >> $LOGFILE
@@ -88,9 +100,11 @@ LOGFILE=${datestamp}/testing.log
       echo "Input file '$1' is not executable or found."
       echo "Couldn't find/execute it after looking with"
       echo "`pwd` as the base directory."
+      kill $PID_HANG
+      exit 1
   fi
   
 # if ther was an error, still need to kill the background job
-trap 'kill $PID_HANG; echo "There was an error"; cat $OUTPUT' ERR
+#trap 'kill $PID_HANG; echo "There was an error"; cat $OUTPUT' ERR
 
 kill $PID_HANG
