Update test_script

diff --git a/testing/test_script b/testing/test_script
--- a/testing/test_script
+++ b/testing/test_script
@@ -59,7 +59,7 @@ if [ "$#" -lt 3 ] || [ $error == 1 ]; then
     echo "  For a parallel MPI run of the large test set, using number of processors in /proc/cpuinfo: "
     echo "  $ ./test_script executable false large"
     kill $PID_HANG
-    exit
+    exit 1
 fi
 
 datestamp=`date +%d%b%Y_%H%M%S`
@@ -80,10 +80,6 @@ LOGFILE=${datestamp}/testing.log
           	$1 < ./test_cases/$i > $OUTPUT
           fi
           python testing.py $OUTPUT $i | tee -a $LOGFILE
-          if [ "$?" != "0" ]
-          then
-              cat $OUTPUT
-          fi
       done
       echo Tests completed in $SECONDS seconds on $(date) | tee -a $LOGFILE
       echo ----------------------------------------------------------------------\n >> $LOGFILE
@@ -93,5 +89,8 @@ LOGFILE=${datestamp}/testing.log
       echo "Couldn't find/execute it after looking with"
       echo "`pwd` as the base directory."
   fi
+  
+# if ther was an error, still need to kill the background job
+trap 'kill $PID_HANG; echo "There was an error"; cat $OUTPUT' ERR
 
 kill $PID_HANG
